const OpenweathermapService = require('../utils/openweathermap/Openweathermap');
const User = require('./User');


'use strict';



const findAll = async () => {

    const dataObject = await User.findAll();
    const dataList = [];
    Object.keys(dataObject).forEach((key) => {
    dataList.push({
        id: key, // The unique key generated by push()
        ...dataObject[key] // The rest of the object properties
      });
    });
    return dataList;
}


const createUser = async (req, res) => {
        try {
            const { name, zipCode, latitude, longitude } = req.body || {};

            if (!name || !zipCode) {
                return res.status(400).json({ error: 'name and zipCode are required' });
            }
            
            // fetch timezone based on latitude and longitude if provided from openweathermap
            let timezone = "";
            let openWeatherData = null;
            if (latitude && longitude) {
                const data = await OpenweathermapService.fetchWeatherData(latitude, longitude);
                timezone = data.timezone; // Placeholder
                openWeatherData = data; // Placeholder
                // fetch from openweathermap API using latitude and longitude
                console.log(`Fetched timezone ${timezone} for coordinates (${latitude}, ${longitude})`);
            }


            const user = await User.create({ name, zipCode, latitude, longitude, timezone, openWeatherData });
            return res.status(201).json(user);
        } catch (err) {
            console.error('User creation failed:', err);
            return res.status(500).json({ error: 'Internal server error' });
        }
}

const updateUser = async (req, res) => {
    // Implementation for updating a user
    try{
        const { name, zipCode, latitude, longitude, id } = req.body || {};

            if (!name || !zipCode) {
                return res.status(400).json({ error: 'name and zipCode are required' });
            }
            
            // fetch timezone based on latitude and longitude if provided from openweathermap
            let timezone = null;
            let openWeatherData = null;
            if (latitude && longitude) {
                const data = await OpenweathermapService.fetchWeatherData(latitude, longitude);
                timezone = data.timezone; // Placeholder
                openWeatherData = data; // Placeholder
                // fetch from openweathermap API using latitude and longitude
                console.log(`Fetched timezone ${timezone} for coordinates (${latitude}, ${longitude})`);
            }

            const user = await User.update({ name, zipCode, latitude, longitude, timezone, openWeatherData, id });
            return user;

    }catch (err) {
            console.error('User update failed:', err);
            return res.status(500).json({ error: 'Internal server error' });
        }
}

const deleteUser = async (req, res) => {
    // Implementation for deleting a user
    try{
        console.log(req.params.id);
        const { id } = req.params || {};

            if (!id) {
                return res.status(400).json({ error: 'id is required' });
            }

            const user = await User.deleteUser({ id });
            return user;

    }catch (err) {
            console.error('User delete failed:', err);
            return res.status(500).json({ error: 'Internal server error' });
        }
}


module.exports = {createUser, updateUser, findAll, deleteUser};